### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TwoPizza9621536**
More quotes from past live streams. A new viewer will has to see the past live streams for a better experience and quoting.

### CODE REVIEW

**Comment by TwoPizza9621536** [comment]
Also experience as in will watch the whole stream.

**Comment by scj643** [comment]
The `I'm in danger` quote is not applicable since it's not original.

**Comment by TwoPizza9621536** [comment]
Updated it

**Comment by TwoPizza9621536** [comment]
@scj643 Merge conflict fixed and added 1 quote. Merge it before another quote needs to added.

**Pull request merged**
